return {
  ["workshop-1185229307"]={
    configuration_options={
      CAMERA=true,
      DAMAGE_NUMBERS=true,
      DAMAGE_RESISTANCE=true,
      FRAME_PHASES=true,
      GLOBAL=false,
      GLOBAL_NUMBERS=false,
      HEADER_CLIENT=false,
      HEADER_SERVER=false,
      HORIZONTAL_OFFSET=0,
      TAG="EPIC",
      TRANSLATOR=false,
      WETNESS_METER=true 
    },
    enabled=true 
  },
  ["workshop-1250339413"]={ configuration_options={  }, enabled=true },
  ["workshop-1530801499"]={
    configuration_options={ ArrowsignEnable=false, HungerCost=1, Ownership=false, SanityCost=1 },
    enabled=true 
  },
  ["workshop-1686705509"]={ configuration_options={  }, enabled=true },
  ["workshop-1818688368"]={ configuration_options={  }, enabled=true },
  ["workshop-1898292532"]={
    configuration_options={
      antlion=true,
      atrium_gate=true,
      bearger=true,
      beequeenhive=true,
      crabking=true,
      deerclops=true,
      dragonfly=true,
      hound=true,
      klaus_sack=true,
      lunarrift_portal=true,
      malbatross=true,
      prime_mate=true,
      tips_method=1,
      toadstool=true 
    },
    enabled=true 
  },
  ["workshop-1931546689"]={
    configuration_options={ icon=0, ison=0, radius=5, recipe=0, skin=1 },
    enabled=true 
  },
  ["workshop-1998081438"]={ configuration_options={ StackMode=true, StackRadius=10 }, enabled=true },
  ["workshop-2323630362"]={
    configuration_options={ no_rotten=false, quick_plant=true, to_auto_aligning=true, to_oversize=true },
    enabled=true 
  },
  ["workshop-2494857748"]={
    configuration_options={
      [""]=false,
      guano=true,
      halloween_ornament=true,
      halloweencandy=true,
      houndstooth=true,
      interval=5,
      lang=true,
      lucky_goldnugget=true,
      myth_toy=false,
      poop=true,
      rottenegg=false,
      silk=false,
      sketch=true,
      spidergland=true,
      spoiled_food=true,
      stinger=true,
      twigs=false,
      winter_food=true,
      winter_ornament=true,
      winter_ornament_boss=true,
      winter_ornament_light=false 
    },
    enabled=true 
  },
  ["workshop-2527328931"]={
    configuration_options={
      Animal=false,
      BuildRepair=false,
      ChopTime=0.01,
      CookTime=998,
      DryTime=999,
      FishTime=999,
      HSHU=false,
      MineTime=0.01,
      Others=true,
      Pick=true,
      Plant=false 
    },
    enabled=true 
  },
  ["workshop-2784048339"]={
    configuration_options={
      Craft="Easy",
      Destroyable="DestroyByAll",
      Language="Ch",
      Slots=80,
      srfresh=0,
      sroom_drag=true 
    },
    enabled=true 
  },
  ["workshop-2902364746"]={ configuration_options={ mode="Share" }, enabled=true },
  ["workshop-2995319954"]={
    configuration_options={
      FLIPMOON=false,
      HIDECAVECLOCK=false,
      HUDSCALEFACTOR=100,
      SEASONOPTIONS="Clock",
      SHOWBEAVERNESS=true,
      SHOWCLOCKTEXT=true,
      SHOWMAXONNUMBERS=true,
      SHOWMOON=1,
      SHOWNAUGHTINESS=true,
      SHOWNEXTFULLMOON=true,
      SHOWSTATNUMBERS=true,
      SHOWTEMPBADGES=true,
      SHOWTEMPERATURE=true,
      SHOWWANINGMOON=true,
      SHOWWORLDTEMP=false,
      UNIT="T" 
    },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=250 }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-599498678"]={ configuration_options={  }, enabled=true },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="chs",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-737932010"]={
    configuration_options={
      amount_of_numbers="default",
      display_mode="waving",
      dmg_only="on",
      show_decimal_points="no" 
    },
    enabled=true 
  } 
}